/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as MetronomeRouteImport } from './routes/metronome'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SongSongIdRouteImport } from './routes/song.$songId'
import { Route as SongEditSongIdRouteImport } from './routes/song-edit.$songId'
import { Route as SetlistsSetlistIdRouteImport } from './routes/setlists/$setlistId'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as SongSongIdEditRouteImport } from './routes/song.$songId.edit'
import { Route as SetlistsSetlistIdPlayRouteImport } from './routes/setlists/$setlistId/play'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomeRoute = MetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdRoute = SongSongIdRouteImport.update({
  id: '/song/$songId',
  path: '/song/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SongEditSongIdRoute = SongEditSongIdRouteImport.update({
  id: '/song-edit/$songId',
  path: '/song-edit/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsSetlistIdRoute = SetlistsSetlistIdRouteImport.update({
  id: '/setlists/$setlistId',
  path: '/setlists/$setlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdEditRoute = SongSongIdEditRouteImport.update({
  id: '/song/$songId/edit',
  path: '/song/$songId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsSetlistIdPlayRoute = SetlistsSetlistIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SetlistsSetlistIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/song-edit/$songId': typeof SongEditSongIdRoute
  '/song/$songId': typeof SongSongIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/setlists/$setlistId/play': typeof SetlistsSetlistIdPlayRoute
  '/song/$songId/edit': typeof SongSongIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/song-edit/$songId': typeof SongEditSongIdRoute
  '/song/$songId': typeof SongSongIdRoute
  '/profile': typeof ProfileIndexRoute
  '/setlists': typeof SetlistsIndexRoute
  '/setlists/$setlistId/play': typeof SetlistsSetlistIdPlayRoute
  '/song/$songId/edit': typeof SongSongIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/setlists/$setlistId': typeof SetlistsSetlistIdRouteWithChildren
  '/song-edit/$songId': typeof SongEditSongIdRoute
  '/song/$songId': typeof SongSongIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/setlists/$setlistId/play': typeof SetlistsSetlistIdPlayRoute
  '/song/$songId/edit': typeof SongSongIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metronome'
    | '/tuner'
    | '/profile/settings'
    | '/setlists/$setlistId'
    | '/song-edit/$songId'
    | '/song/$songId'
    | '/profile/'
    | '/setlists/'
    | '/setlists/$setlistId/play'
    | '/song/$songId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metronome'
    | '/tuner'
    | '/profile/settings'
    | '/setlists/$setlistId'
    | '/song-edit/$songId'
    | '/song/$songId'
    | '/profile'
    | '/setlists'
    | '/setlists/$setlistId/play'
    | '/song/$songId/edit'
  id:
    | '__root__'
    | '/'
    | '/metronome'
    | '/tuner'
    | '/profile/settings'
    | '/setlists/$setlistId'
    | '/song-edit/$songId'
    | '/song/$songId'
    | '/profile/'
    | '/setlists/'
    | '/setlists/$setlistId/play'
    | '/song/$songId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetronomeRoute: typeof MetronomeRoute
  TunerRoute: typeof TunerRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  SetlistsSetlistIdRoute: typeof SetlistsSetlistIdRouteWithChildren
  SongEditSongIdRoute: typeof SongEditSongIdRoute
  SongSongIdRoute: typeof SongSongIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SetlistsIndexRoute: typeof SetlistsIndexRoute
  SongSongIdEditRoute: typeof SongSongIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronome': {
      id: '/metronome'
      path: '/metronome'
      fullPath: '/metronome'
      preLoaderRoute: typeof MetronomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId': {
      id: '/song/$songId'
      path: '/song/$songId'
      fullPath: '/song/$songId'
      preLoaderRoute: typeof SongSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song-edit/$songId': {
      id: '/song-edit/$songId'
      path: '/song-edit/$songId'
      fullPath: '/song-edit/$songId'
      preLoaderRoute: typeof SongEditSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$setlistId': {
      id: '/setlists/$setlistId'
      path: '/setlists/$setlistId'
      fullPath: '/setlists/$setlistId'
      preLoaderRoute: typeof SetlistsSetlistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId/edit': {
      id: '/song/$songId/edit'
      path: '/song/$songId/edit'
      fullPath: '/song/$songId/edit'
      preLoaderRoute: typeof SongSongIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$setlistId/play': {
      id: '/setlists/$setlistId/play'
      path: '/play'
      fullPath: '/setlists/$setlistId/play'
      preLoaderRoute: typeof SetlistsSetlistIdPlayRouteImport
      parentRoute: typeof SetlistsSetlistIdRoute
    }
  }
}

interface SetlistsSetlistIdRouteChildren {
  SetlistsSetlistIdPlayRoute: typeof SetlistsSetlistIdPlayRoute
}

const SetlistsSetlistIdRouteChildren: SetlistsSetlistIdRouteChildren = {
  SetlistsSetlistIdPlayRoute: SetlistsSetlistIdPlayRoute,
}

const SetlistsSetlistIdRouteWithChildren =
  SetlistsSetlistIdRoute._addFileChildren(SetlistsSetlistIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetronomeRoute: MetronomeRoute,
  TunerRoute: TunerRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  SetlistsSetlistIdRoute: SetlistsSetlistIdRouteWithChildren,
  SongEditSongIdRoute: SongEditSongIdRoute,
  SongSongIdRoute: SongSongIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SetlistsIndexRoute: SetlistsIndexRoute,
  SongSongIdEditRoute: SongSongIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
